#!/bin/bash

export LANG=en-US
export TZ=:Europe/Warsaw
# temporary solution, for more details see PREMIUMAPP-3309
export COBALT_ENABLE_OVERRIDES=1
export DeviceIdentification_deviceidentification='{"firmwareversion":"1.0.0","chipset":"S905X4"}'

#export THUNDER_ACCESS=127.0.0.1:9998

elf_loader_sandbox --evergreen_library=app/nplb/lib/libnplb.so --evergreen_content=app/nplb/content
