#!/bin/sh

export LANG=en-US
export TZ=:Europe/Warsaw
# temporary solution, for more details see PREMIUMAPP-3309
export COBALT_ENABLE_OVERRIDES=1
export DeviceIdentification_deviceidentification='{"firmwareversion":"1.0.0","chipset":"S905X4"}'

elf_loader_sandbox --evergreen_library=app/nplb/lib/libnplb.so --evergreen_content=app/nplb/content --gtest_output="xml:nplb.xml"
