#!/bin/bash

# If not stated otherwise in this file or this component's LICENSE file the
# following copyright and licenses apply:
#
# Copyright 2025 RDK Management
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

test -f .env && source $_

META_ROOT=$(readlink -m "$(dirname "${BASH_SOURCE[0]}")")
SETUP_SCRIPT=deps/bolt/setup-environment

if [ ! -f ${SETUP_SCRIPT} ]; then
  ${META_ROOT}/repo-sync
fi

if [ -f ${SETUP_SCRIPT} ]; then
  source ${SETUP_SCRIPT}
fi

if [[ -n "${BUILDDIR}" && "$(pwd)" == "$(readlink -m ${BUILDDIR})" ]]; then
  cat ${META_ROOT}/conf/conf-notes.txt

  DIR_FILE=$(basename ${META_ROOT}).done

  if [ ! -f conf/${DIR_FILE} ]; then
    echo "BBLAYERS:append = \" ${META_ROOT}\"" >> conf/bblayers.conf
    echo ${META_ROOT} > conf/${DIR_FILE}
  fi
fi
